### ISSUE TITLE
Reduce Headshot Size - Homepage

### ISSUE THREAD

**Issue by cngodles** [ryleelyman/ryleelyman.github.io#3]
`https://ryleealanza.org/`

This thing is huge!
`https://ryleealanza.org/assets/img/headshot2.jpg`

If you are going to display it 200px wide, I'd make a headshot2-200px.jpg that was well under 50K. The current one takes 57 seconds to load for me.

**Comment by robbielyman** [comment]
Thanks for the feedback. I reduced the headshot size 

d75ad6f97f89407e110c99ab3e57b2f860476bac
